name: Envio Diario de Reporte Premium

on:
  schedule:
    # Ejecuta todos los días a las 10:00 AM UTC (Ajusta este CRON a tu horario deseado)
    - cron: '0 10 * * *' 
  workflow_dispatch:
    # Esto te permite ejecutar el script manualmente desde la interfaz de GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 1. Configuración de Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    # 2. Instalación de Dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instala todas las librerías necesarias
        pip install yfinance google-api-python-client google-auth-oauthlib google-auth pandas numpy pandas-ta
        
    # 3. Ejecución del Script
    - name: Run Python Script
      # Pasa los secrets como variables de entorno al script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python Premium.py
